namespace CloudTextToSound
{
    /// <summary>
    /// 音色枚举类型扩展
    /// </summary>
    public static class VoiceTimbreExtention
    {
        /// <summary>
        /// 获取音色ID
        /// </summary>
        /// <param name="voiceTimbreType"></param>
        /// <returns></returns>
        /// <exception cref="CloudTextToSoundException"></exception>
        public static int GetID(this VoiceTimbreType voiceTimbreType)
        {
            switch (voiceTimbreType)
            {
                case VoiceTimbreType.智逍遥:
                    return 10510000;
                case VoiceTimbreType.智瑜:
                    return 1001;
                case VoiceTimbreType.智聆:
                    return 1002;
                case VoiceTimbreType.智美:
                    return 1003;
                case VoiceTimbreType.智云:
                    return 1004;
                case VoiceTimbreType.智莉:
                    return 1005;
                case VoiceTimbreType.智娜:
                    return 1007;
                case VoiceTimbreType.智琪:
                    return 1008;
                case VoiceTimbreType.智芸:
                    return 1009;
                case VoiceTimbreType.智华:
                    return 1010;
                case VoiceTimbreType.智蓉:
                    return 1017;
                case VoiceTimbreType.智靖:
                    return 1018;
                case VoiceTimbreType.WeJack:
                    return 1050;
                case VoiceTimbreType.WeRose:
                    return 1051;
                case VoiceTimbreType.智言:
                    return 101006;
                case VoiceTimbreType.智燕:
                    return 101011;
                case VoiceTimbreType.智丹:
                    return 101012;
                case VoiceTimbreType.智辉:
                    return 101013;
                case VoiceTimbreType.智宁:
                    return 101014;
                case VoiceTimbreType.智萌:
                    return 101015;
                case VoiceTimbreType.智甜:
                    return 101016;
                case VoiceTimbreType.智彤:
                    return 101019;
                case VoiceTimbreType.智刚:
                    return 101020;
                case VoiceTimbreType.智瑞:
                    return 101021;
                case VoiceTimbreType.智虹:
                    return 101022;
                case VoiceTimbreType.智萱:
                    return 101023;
                case VoiceTimbreType.智皓:
                    return 101024;
                case VoiceTimbreType.智薇:
                    return 101025;
                case VoiceTimbreType.智希:
                    return 101026;
                case VoiceTimbreType.智梅:
                    return 101027;
                case VoiceTimbreType.智洁:
                    return 101028;
                case VoiceTimbreType.智凯:
                    return 101029;
                case VoiceTimbreType.智柯:
                    return 101030;
                case VoiceTimbreType.智奎:
                    return 101031;
                case VoiceTimbreType.智芳:
                    return 101032;
                case VoiceTimbreType.智蓓:
                    return 101033;
                case VoiceTimbreType.智莲:
                    return 101034;
                case VoiceTimbreType.智依:
                    return 101035;
                case VoiceTimbreType.智川:
                    return 101040;
                case VoiceTimbreType.WeJack精品:
                    return 101050;
                case VoiceTimbreType.WeRose精品:
                    return 101051;
                case VoiceTimbreType.智味:
                    return 101052;
                case VoiceTimbreType.智方:
                    return 101053;
                case VoiceTimbreType.智友:
                    return 101054;
                case VoiceTimbreType.智付:
                    return 101055;
                case VoiceTimbreType.智林:
                    return 101056;
                case VoiceTimbreType.爱小广:
                    return 301000;
                case VoiceTimbreType.爱小栋:
                    return 301001;
                case VoiceTimbreType.爱小海:
                    return 301002;
                case VoiceTimbreType.爱小霞:
                    return 301003;
                case VoiceTimbreType.爱小玲:
                    return 301004;
                case VoiceTimbreType.爱小章:
                    return 301005;
                case VoiceTimbreType.爱小峰:
                    return 301006;
                case VoiceTimbreType.爱小亮:
                    return 301007;
                case VoiceTimbreType.爱小博:
                    return 301008;
                case VoiceTimbreType.爱小芸:
                    return 301009;
                case VoiceTimbreType.爱小秋:
                    return 301010;
                case VoiceTimbreType.爱小芳:
                    return 301011;
                case VoiceTimbreType.爱小琴:
                    return 301012;
                case VoiceTimbreType.爱小康:
                    return 301013;
                case VoiceTimbreType.爱小辉:
                    return 301014;
                case VoiceTimbreType.爱小璐:
                    return 301015;
                case VoiceTimbreType.爱小阳:
                    return 301016;
                case VoiceTimbreType.爱小泉:
                    return 301017;
                case VoiceTimbreType.爱小昆:
                    return 301018;
                case VoiceTimbreType.爱小诚:
                    return 301019;
                case VoiceTimbreType.爱小岚:
                    return 301020;
                case VoiceTimbreType.爱小茹:
                    return 301021;
                case VoiceTimbreType.爱小蓉:
                    return 301022;
                case VoiceTimbreType.爱小燕:
                    return 301023;
                case VoiceTimbreType.爱小莲:
                    return 301024;
                case VoiceTimbreType.爱小武:
                    return 301025;
                case VoiceTimbreType.爱小雪:
                    return 301026;
                case VoiceTimbreType.爱小媛:
                    return 301027;
                case VoiceTimbreType.爱小娴:
                    return 301028;
                case VoiceTimbreType.爱小涛:
                    return 301029;
                case VoiceTimbreType.爱小溪:
                    return 301030;
                case VoiceTimbreType.爱小树:
                    return 301031;
                case VoiceTimbreType.爱小荷:
                    return 301032;
                case VoiceTimbreType.爱小叶:
                    return 301033;
                case VoiceTimbreType.爱小杭:
                    return 301034;
                case VoiceTimbreType.爱小梅:
                    return 301035;
                case VoiceTimbreType.爱小柯:
                    return 301036;
                case VoiceTimbreType.爱小静:
                    return 301037;
                case VoiceTimbreType.爱小桃:
                    return 301038;
                case VoiceTimbreType.智妍:
                    return 401000;
                case VoiceTimbreType.温柔智萱:
                    return 401001;
                case VoiceTimbreType.智飞:
                    return 401002;
                case VoiceTimbreType.智悦:
                    return 401003;
                case VoiceTimbreType.智海:
                    return 401004;
                case VoiceTimbreType.智凡:
                    return 401005;
                case VoiceTimbreType.智航:
                    return 401006;
                case VoiceTimbreType.智婷:
                    return 401007;
                case VoiceTimbreType.智霞:
                    return 401008;
                default:
                    throw new CloudTextToSoundException("未知的语音类型");
            }
        }
    }
}
